version: 1.0.{build}

branches:
  only:
    - release
  except:
    - master
    - lazarus


# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: kBUOx4ER4aHlxqZZlLTOGg==
  nodejs_version: "7"
  BINW32_PATH: '%APPVEYOR_BUILD_FOLDER%\..\binw32'
  PPDIR: '%APPVEYOR_BUILD_FOLDER%\..\freepascal\fpc\bin\i386-win32'
  BINW32_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/binw32.7z'
  DOWNLOAD_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/download4lazarus.js'

install:
  - rm appveyor.yml
  - cd ..
  - appveyor DownloadFile %BINW32_DL%
  - 7z x binw32.7z -o%APPVEYOR_BUILD_FOLDER%\.. -y  
  - npm install @octokit/rest
  - npm install download
  - npm install unzip
  - appveyor DownloadFile %DOWNLOAD_DL% -FileName %APPVEYOR_BUILD_FOLDER%\..\download4lazarus.js
  - node download4lazarus.js

build_script:
  - SET ORIGINAL_PATH=%PATH%
  - SET PATH=%PPDIR%;%BINW32_PATH%;%WINDIR%\System32
  - cd %APPVEYOR_BUILD_FOLDER%
  - make clean all

after_build:
  - SET PATH=%ORIGINAL_PATH%
  - 7z a -tzip lazarus.zip %APPVEYOR_BUILD_FOLDER%
  - move /Y lazarus.zip %APPVEYOR_BUILD_FOLDER%
  
artifacts:
  - path: lazarus.zip
    name: lazarus

deploy:
  tag: lazarus4np-v$(appveyor_build_version)
  release: 'Lazarus for NewPascal v$(appveyor_build_version)'
  description: 'Release of Lazarus for NewPascal'
  provider: GitHub
  auth_token:
    secure: KcYu4lP5AV4BYpPzpV2CQGucX7BpAsyRChrjOhZXH4z1DDtc5J0J6WvJ1hTr7VSI
  artifact: lazarus
  draft: false
  prerelease: false
  on:
    branch: release                 # release from master branch only
    appveyor_repo_tag: false       # ?deploy on tag push only

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy: off